export default function useTruesightV2() {
  return {
    tokenList: {
      data: [
        {
          id: 1,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 2,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 3,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 4,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 5,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 6,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 7,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 8,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 9,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 10,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 11,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 12,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 13,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 14,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 15,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 16,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 17,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 18,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 19,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 20,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
        {
          id: 21,
          symbol: 'KNC',
          tokenName: 'Kyber Network Crystal',
          chain: 1,
          price: '0.00000004234',
          change: '20%',
          '24hVolume': '500M',
          kyberscore: '88',
        },
      ],
      totalItems: 21,
    },
  }
}
