import { PoolType } from "@kyberswap/liquidity-widgets";
import { Dex } from "@kyberswap/zap-migration-widgets";

export const dexMapping: Record<PoolType | Dex, string> = {
  [PoolType.DEX_UNISWAP_V4]: "Uniswap V4",
  [PoolType.DEX_UNISWAPV3]: "Uniswap V3",
  [PoolType.DEX_PANCAKESWAPV3]: "PancakeSwap V3",
  [PoolType.DEX_METAVAULTV3]: "MetaVault V3",
  [PoolType.DEX_SUSHISWAPV3]: "SushiSwap V3",
  [PoolType.DEX_LINEHUBV3]: "LineHub V3",
  [PoolType.DEX_SWAPMODEV3]: "SwapMode V3",
  [PoolType.DEX_KOICL]: "KOI CL",
  [PoolType.DEX_THRUSTERV3]: "Thruster V3",
  [PoolType.DEX_PANCAKESWAPV2]: "PancakeSwap V2",
  [PoolType.DEX_UNISWAPV2]: "Uniswap V2",
  [PoolType.DEX_SUSHISWAPV2]: "SushiSwap V2",
  [PoolType.DEX_QUICKSWAPV2]: "QuickSwap V2",
  [PoolType.DEX_THRUSTERV2]: "Thruster V2",
  [PoolType.DEX_SWAPMODEV2]: "SwapMode V2",
  [PoolType.DEX_THENAFUSION]: "Thena",
  [PoolType.DEX_CAMELOTV3]: "Camelot V3",
  [PoolType.DEX_QUICKSWAPV3ALGEBRA]: "QuickSwap",
  [PoolType.DEX_PANGOLINSTANDARD]: "Pangolin Standard",
  [PoolType.DEX_KODIAK_V3]: "Kodiak V3",
  [PoolType.DEX_KODIAK_V2]: "Kodiak V2",
  [PoolType.DEX_SQUADSWAP_V3]: "Squad Swap V3",
  [PoolType.DEX_SQUADSWAP_V2]: "Squad Swap V2",

  [Dex.DEX_UNISWAP_V4]: "Uniswap V4",
  [Dex.DEX_UNISWAPV3]: "Uniswap V3",
  [Dex.DEX_PANCAKESWAPV3]: "PancakeSwap V3",
  [Dex.DEX_METAVAULTV3]: "MetaVault V3",
  [Dex.DEX_SUSHISWAPV3]: "SushiSwap V3",
  [Dex.DEX_LINEHUBV3]: "LineHub V3",
  [Dex.DEX_SWAPMODEV3]: "SwapMode V3",
  [Dex.DEX_KOICL]: "KOI CL",
  [Dex.DEX_THRUSTERV3]: "Thruster V3",
  [Dex.DEX_UNISWAPV2]: "Uniswap V2",
  [Dex.DEX_KODIAK_V3]: "Kodiak V3",
  [Dex.DEX_SQUADSWAP_V3]: "Squad Swap V3",
  [Dex.DEX_SQUADSWAP_V2]: "Squad Swap V2",
  [Dex.DEX_THENAFUSION]: "Thena",
  [Dex.DEX_CAMELOTV3]: "Camelot V3",
  [Dex.DEX_QUICKSWAPV3ALGEBRA]: "QuickSwap",
};
