export const dexMapping = {
  DEX_UNISWAPV3: "Uniswap V3",
  DEX_PANCAKESWAPV3: "PancakeSwap V3",
  DEX_METAVAULTV3: "MetaVault V3",
  DEX_SUSHISWAPV3: "SushiSwap V3",
  DEX_LINEHUBV3: "LineHub V3",
  DEX_CURVEV3: "Curve V3",
  DEX_SWAPMODEV3: "SwapMode V3",
  DEX_KOICL: "KOI CL",
  DEX_THRUSTERV3: "Thruster V3",
  DEX_PANCAKESWAPV2: "PancakeSwap V2",
  DEX_UNISWAPV2: "Uniswap V2",
  DEX_SUSHISWAPV2: "SushiSwap V2",
  DEX_QUICKSWAPV2: "QuickSwap V2",
  DEX_THRUSTERV2: "Thruster V2",
  DEX_SWAPMODEV2: "SwapMode V2",
  DEX_THENAFUSION: "Thena",
  DEX_CAMELOTV3: "Camelot V3",
  DEX_QUICKSWAPV3ALGEBRA: "QuickSwap",
  DEX_PANGOLINSTANDARD: "Pangolin Standard",
};
