import { Currency } from '@kyberswap/ks-sdk-core'
import { useCallback } from 'react'

import { Field } from 'state/swap/actions'
import { TRANSACTION_TYPE } from 'state/transactions/type'

// Analytics are disabled app-wide: these hooks accept events and discard them, so nothing leaves the
// browser. The event taxonomy and the hook signatures are kept intact so the ~86 call sites across the app
// remain valid, and so a provider can be reintroduced behind this single seam.

export enum TRACKING_EVENT_TYPE {
  WALLET_CONNECT_CLICK,
  WALLET_CONNECT_ACCEPT_TERM_CLICK,
  WALLET_CONNECT_WALLET_CLICK,
  SWAP_INITIATED,
  SWAP_CONFIRMED,
  SWAP_COMPLETED,
  SWAP_SETTINGS_CLICK,
  SWAP_TUTORIAL_CLICK,
  SWAP_TOKEN_INFO_CLICK,
  SWAP_MORE_INFO_CLICK,
  SWAP_DISPLAY_SETTING_CLICK,
  DEGEN_MODE_TOGGLE,
  ADD_RECIPIENT_CLICKED,
  SLIPPAGE_CHANGED,
  LIVE_CHART_ON_OFF,
  TRADING_ROUTE_ON_OFF,
  LIVE_CHART_ON_MOBILE,
  PRO_CHART_CLICKED,
  BASIC_CHART_CLICKED,
  TRADING_ROUTE_ON_MOBILE,
  TOKEN_INFO_CHECKED,
  TOKEN_SWAP_LINK_SHARED,
  ADD_FAVORITE_CHAIN,
  REMOVE_FAVORITE_CHAIN,
  CREATE_POOL_INITITATED,
  CREATE_POOL_COMPLETED,
  CREATE_POOL_LINK_SHARED,
  ADD_LIQUIDITY_INITIATED,
  ADD_LIQUIDITY_COMPLETED,
  REMOVE_LIQUIDITY_COMPLETED,
  REMOVE_LIQUIDITY_INITIATED,
  MIGRATE_LIQUIDITY_INITIATED,
  CLAIM_REWARDS_INITIATED,
  IMPORT_POOL_INITIATED,
  MYPOOLS_STAKED_VIEWED,
  MYPOOLS_POOLS_VIEWED,
  MYPOOLS_CLICK_SUBSCRIBE_BTN,

  FARMS_ACTIVE_VIEWED,
  FARMS_ENDING_VIEWED,
  FARMS_UPCOMING_VIEWED,
  FARMS_MYVESTING_VIEWED,
  INDIVIDUAL_REWARD_HARVESTED,
  ALL_REWARDS_HARVESTED,
  SINGLE_REWARD_CLAIMED,
  ALL_REWARDS_CLAIMED,
  ABOUT_SWAP_CLICKED,
  ABOUT_START_EARNING_CLICKED,
  ABOUT_VIEW_FARMS_CLICKED,
  ABOUT_CREATE_NEW_POOL_CLICKED,
  ABOUT_STAKE_KNC_CLICKED,
  ANALYTICS_MENU_CLICKED,
  BLOG_MENU_CLICKED,
  DISCOVER_TRENDING_SOON_CLICKED,
  DISCOVER_TRENDING_CLICKED,
  DISCOVER_SWAP_INITIATED,
  DISCOVER_SWAP_DISCOVER_MORE_CLICKED,
  DISCOVER_SWAP_SEE_HERE_CLICKED,
  DISCOVER_SWAP_BUY_NOW_CLICKED,
  DISCOVER_SWAP_MORE_INFO_CLICKED,
  DISCOVER_SWAP_BUY_NOW_POPUP_CLICKED,
  ELASTIC_CREATE_POOL_INITIATED,
  ELASTIC_CREATE_POOL_COMPLETED,
  ELASTIC_MYPOOLS_ELASTIC_POOLS_CLICKED,
  ELASTIC_POOLS_ELASTIC_POOLS_CLICKED,
  ELASTIC_ADD_LIQUIDITY_INITIATED,
  ELASTIC_ADD_LIQUIDITY_IN_LIST_INITIATED,
  ELASTIC_ADD_LIQUIDITY_COMPLETED,
  ELASTIC_ADD_LIQUIDITY_ADD_NEW_POSITION,
  ELASTIC_ADD_LIQUIDITY_CLICK_TO_REMOVE_POSITION,
  ELASTIC_ADD_LIQUIDITY_SELECT_RANGE_FOR_POOL,
  ELASTIC_ADD_LIQUIDITY_CLICK_SWAP,
  ELASTIC_ADD_LIQUIDITY_CLICK_PRICE_CHART,
  ELASTIC_ADD_LIQUIDITY_CLICK_POOL_ANALYTIC,
  ELASTIC_REMOVE_LIQUIDITY_INITIATED,
  ELASTIC_REMOVE_LIQUIDITY_COMPLETED,
  ELASTIC_INCREASE_LIQUIDITY_INITIATED,
  ELASTIC_INCREASE_LIQUIDITY_COMPLETED,
  ELASTIC_COLLECT_FEES_INITIATED,
  ELASTIC_COLLECT_FEES_COMPLETED,
  ELASTIC_DEPOSIT_LIQUIDITY_COMPLETED,
  ELASTIC_WITHDRAW_LIQUIDITY_COMPLETED,
  ELASTIC_STAKE_LIQUIDITY_COMPLETED,
  ELASTIC_UNSTAKE_LIQUIDITY_COMPLETED,
  ELASTIC_INDIVIDUAL_REWARD_HARVESTED,
  ELASTIC_ALLS_REWARD_HARVESTED,
  ELASTIC_ALL_REWARD_CLAIMED,
  FAUCET_MENU_CLICKED,
  FAUCET_REQUEST_INITIATED,
  FAUCET_REQUEST_COMPLETED,
  DISCOVER_CLICK_SUBSCRIBE_TRENDING_SOON,
  DISCOVER_SUBSCRIBE_TRENDING_SOON_SUCCESS,
  DISCOVER_UNSUBSCRIBE_TRENDING_SOON_SUCCESS,

  // for tutorial swap
  TUTORIAL_CLICK_START,
  TUTORIAL_CLICK_DONE,
  TUTORIAL_CLICK_DENY,
  TUTORIAL_VIEW_VIDEO_SWAP,

  // MEV Protection
  MEV_CLICK_ADD_MEV,
  MEV_ADD_CLICK_MODAL,
  MEV_ADD_RESULT,

  BANNER_CLICK,
  CLOSE_BANNER_CLICK,

  FARM_UNDER_EARN_TAB_CLICK,

  // bridge
  BRIDGE_CLICK_REVIEW_TRANSFER,
  BRIDGE_CLICK_TRANSFER,
  BRIDGE_TRANSACTION_SUBMIT,
  BRIDGE_CLICK_HISTORY_TRANSFER_TAB,
  BRIDGE_CLICK_SUBSCRIBE_BTN,
  BRIDGE_CLICK_DISCLAIMER,
  BRIDGE_CLICK_UNDERSTAND_IN_FIRST_TIME_VISIT,

  // Kyber DAO
  KYBER_DAO_STAKE_CLICK,
  KYBER_DAO_UNSTAKE_CLICK,
  KYBER_DAO_DELEGATE_CLICK,
  KYBER_DAO_VOTE_CLICK,
  KYBER_DAO_CLAIM_CLICK,
  KYBER_DAO_FEATURE_REQUEST_CLICK,
  GAS_REFUND_CLAIM_CLICK,
  GAS_REFUND_SOURCE_CLICK,

  // notification
  NOTIFICATION_CLICK_MENU,
  NOTIFICATION_SELECT_TOPIC,
  NOTIFICATION_DESELECT_TOPIC,

  ANNOUNCEMENT_CLICK_BELL_ICON_OPEN_POPUP,
  ANNOUNCEMENT_CLICK_TAB_INBOX,
  ANNOUNCEMENT_CLICK_TAB_ANNOUNCEMENT,
  ANNOUNCEMENT_CLICK_ANNOUNCEMENT_MESSAGE,
  ANNOUNCEMENT_CLICK_INBOX_MESSAGE,
  ANNOUNCEMENT_CLICK_CLOSE_POPUP,
  ANNOUNCEMENT_CLICK_CTA_POPUP,
  ANNOUNCEMENT_CLICK_CLEAR_ALL_INBOXES,

  // Limit Order
  LO_PAGE_VIEWED,
  LO_CLICK_PLACE_ORDER,
  LO_PLACE_ORDER_SUCCESS,
  LO_ENTER_DETAIL,
  LO_CLICK_CANCEL_ORDER,
  LO_CANCEL_ORDER_SUBMITTED,
  LO_CLICK_REVIEW_PLACE_ORDER,
  LO_CLICK_CANCEL_TYPE,
  LO_CLICK_GET_STARTED,
  LO_CLICK_WARNING_IN_SWAP,
  LO_REVIEW_OPENED,
  LO_ORDER_PLACED,
  LO_ORDER_FAILED,
  LO_ORDER_FILLED,
  LO_ORDER_CANCELLED,
  LO_SIDE_SELECTED,
  LO_PRICE_SET,
  LO_EXPIRY_CHANGED,
  LO2_CLICK_TAKE,
  LO2_CLICK_PAIR_INVERT,
  LO2_CLICK_HALF,
  LO2_CLICK_MAX,
  LO2_CLICK_WALLET_MAX,
  LO2_CLICK_USE_SWAP,
  LO2_CLICK_FILL,
  LO2_CLICK_RETRY,
  LO2_CLOSE_PANEL,
  LO2_CLICK_RATE_PRESET,
  LO2_CLICK_MARKET_RATE,
  LO2_CLICK_SHARED_BALANCE_REVIEW,

  // Wallet UI
  WUI_WALLET_CLICK,
  WUI_PINNED_WALLET,
  WUI_UNPINNED_WALLET,
  WUI_BUTTON_CLICK,
  WUI_IMPORT_TOKEN_CLICK,
  WUI_TRANSACTION_CLICK,
  WUI_IMPORT_TOKEN_BUTTON_CLICK,

  // Menu header
  MENU_MENU_CLICK,
  MENU_PREFERENCE_CLICK,

  // price alert
  PA_CLICK_TAB_IN_NOTI_CENTER,
  PA_CREATE_SUCCESS,

  // Permit
  PERMIT_CLICK,
  INFINITE_APPROVE_CLICK,
  CUSTOM_APPROVE_CLICK,
  PERMIT_FAILED_TOO_MANY_TIMES,

  ACCEPT_NEW_AMOUNT,

  // earning dashboard
  EARNING_DASHBOARD_CLICK_TOP_LEVEL_SHARE_BUTTON,
  EARNING_DASHBOARD_SHARE_SUCCESSFULLY,
  EARNING_DASHBOARD_CLICK_POOL_EXPAND,
  EARNING_DASHBOARD_CLICK_ALL_CHAINS_BUTTON,
  EARNING_DASHBOARD_CLICK_REFRESH_BUTTON,
  EARNING_DASHBOARD_CLICK_CHANGE_TIMEFRAME_EARNING_CHART,
  EARNING_DASHBOARD_CLICK_ADD_LIQUIDITY_BUTTON,
  EARNING_DASHBOARD_CLICK_CURRENT_CHAIN_BUTTON,
  EARNING_DASHBOARD_VIEW_PAGE,
  EARNING_DASHBOARD_CLICK_SUBSCRIBE,

  // earn banner
  EARN_BANNER_CLICK,
  EARN_BANNER_POOL_CLICK,

  // Swap flow custom events
  SWAP_ROUTE_VIEWED,
  SWAP_REVIEW_OPENED,
  TOKEN_APPROVAL_INITIATED,
  TOKEN_APPROVAL_COMPLETED,
  TOKEN_APPROVAL_FAILED,
  SWAP_FAILED,

  // Swap form interactions
  TOKEN_SELECTED,
  TOKEN_SEARCHED,
  AMOUNT_ENTERED,
  TOKEN_PAIR_REVERSED,
  MAX_BALANCE_CLICKED,

  // Token selector modal interactions. TS_TOKEN_SELECTED is distinct from TOKEN_SELECTED above: it
  // fires inside the modal, so it carries which tab the pick came from and covers every surface the
  // modal serves (swap, limit order, cross-chain), not just the swap form.
  TS_OPENED,
  TS_SEARCHED,
  TS_TAB_SELECTED,
  TS_CHAIN_SWITCHED,
  TS_TOKEN_SELECTED,

  // Swap settings interactions
  TRANSACTION_TIME_LIMIT_CHANGED,
  LIQUIDITY_SOURCES_TOGGLED,

  // Cross-chain execution flow
  CC_ROUTE_VIEWED,
  CC_REVIEW_OPENED,
  CC_SWAP_INITIATED,
  CC_SWAP_COMPLETED,
  CC_SWAP_FAILED,

  // Cross-chain form interactions
  CC_TAB_SELECTED,
  CC_SOURCE_CHAIN_SELECTED,
  CC_DESTINATION_CHAIN_SELECTED,
  CC_RECIPIENT_ADDRESS_ENTERED,
  CC_WALLET_SELECTED,

  // Cross-chain settings interactions
  CC_SETTINGS_OPENED,
  CC_SLIPPAGE_CHANGED,
  CC_ROUTING_SOURCE_TOGGLED,
  CC_SETTINGS_SAVED,

  // Earn: Add Liquidity
  LIQ_POOL_SELECTED,
  LIQ_PRICE_RANGE_PRESET_SELECTED,
  LIQ_PRICE_RANGE_ADJUSTED,
  LIQ_TOKEN_SELECTED,
  LIQ_AMOUNT_ENTERED,
  LIQ_MAX_CLICKED,
  LIQ_HALF_CLICKED,
  LIQ_EXISTING_POSITION_SELECTED,
  LIQ_MAX_SLIPPAGE_CHANGED,
  LIQ_ZAP_SUMMARY_VIEWED,
  LIQ_PREVIEW_CLICKED,
  LIQ_ADDED,
  LIQ_ADD_COMPLETED,
  LIQ_ADD_FAILED,
  LIQ_ADD_CANCELLED,

  // Earn: Migrate
  EARN_MIGRATE_INITIATED,
  EARN_MIGRATE_COMPLETED,
  EARN_MIGRATE_FAILED,

  // Earn: Reposition
  EARN_REPOSITION_INITIATED,
  EARN_REPOSITION_COMPLETED,
  EARN_REPOSITION_FAILED,

  // Earn: Zap Out
  EARN_ZAP_OUT_INITIATED,
  EARN_ZAP_OUT_COMPLETED,
  EARN_ZAP_OUT_FAILED,

  // Earn: Manual Remove
  EARN_MANUAL_REMOVE_INITIATED,
  EARN_MANUAL_REMOVE_COMPLETED,
  EARN_MANUAL_REMOVE_FAILED,

  // Earn: Smart Exit
  EARN_SMART_EXIT_CREATED,
  EARN_SMART_EXIT_COMPLETED,
  EARN_SMART_EXIT_FAILED,
  EARN_SMART_EXIT_CANCELLED,

  // Earn: Pool Discovery
  POOL_CATEGORY_SELECTED,
  POOL_FILTER_APPLIED,
  POOL_SEARCHED,
  POOL_FAVORITED,
  CREATE_POOL_CLICKED,
  TRENDING_POOL_CLICKED,
  FARMING_POOL_CLICKED,

  // Wallet In-App Modal
  WALLET_MODAL_OPENED,
  WALLET_MODAL_CLOSED,
  WALLET_ADDRESS_COPIED,
  WALLET_EXTERNAL_LINK_CLICKED,
  WALLET_PINNED,
  BALANCE_VISIBILITY_TOGGLED,
  WALLET_RECEIVE_CLICKED,
  WALLET_SEND_CLICKED,
  WALLET_SEND_INITIATED,
  WALLET_REWARDS_VIEWED,
  WALLET_TAB_SWITCHED,
  WALLET_TOKEN_CLICKED,
  WALLET_IMPORT_TOKENS_CLICKED,
  WALLET_TOKEN_IMPORTED,

  // Top Right Menu
  MENU_DROPDOWN_OPENED,
  MENU_LINK_CLICKED,
  NOTIFICATION_CENTER_OPENED,
  LANGUAGE_CHANGED,

  // Tip Link Generator
  TIP_LINK_GENERATE_LINK_CLICK,
  TIP_LINK_TRADE,
}

export const NEED_CHECK_SUBGRAPH_TRANSACTION_TYPES: readonly TRANSACTION_TYPE[] = [
  TRANSACTION_TYPE.CLASSIC_ADD_LIQUIDITY,
  TRANSACTION_TYPE.ELASTIC_ADD_LIQUIDITY,
  TRANSACTION_TYPE.CLASSIC_REMOVE_LIQUIDITY,
  TRANSACTION_TYPE.ELASTIC_REMOVE_LIQUIDITY,
  TRANSACTION_TYPE.CLASSIC_CREATE_POOL,
  TRANSACTION_TYPE.ELASTIC_CREATE_POOL,
] as const

export enum CROSS_CHAIN_MIXPANEL_TYPE {
  CROSS_CHAIN_SWAP_INIT = 'cross_chain_swap_init',
  CROSS_CHAIN_SWAP_SUCCESS = 'cross_chain_swap_success',
  CROSS_CHAIN_SWAP_FAILED = 'cross_chain_swap_failed',
}

export const useCrossChainMixpanel = () => {
  const crossChainMixpanelHandler = useCallback((_type: CROSS_CHAIN_MIXPANEL_TYPE, _payload?: any) => {
    // no-op
  }, [])

  return { crossChainMixpanelHandler }
}

export default function useTracking(_currencies?: { [field in Field]?: Currency }) {
  const trackingHandler = useCallback((_type: TRACKING_EVENT_TYPE, _payload?: any) => {
    // no-op
  }, [])

  // No analytics provider ever becomes ready, so call sites that gate on this simply never fire. Widened
  // to `boolean` so the flag stays a meaningful condition for them rather than the literal type `false`.
  return { trackingHandler, isTrackingReady: false as boolean }
}

export const useGlobalTrackingEvents = () => {
  // no-op
}
