module.exports = {
	semi: true,
	singleQuote: true,
	printWidth: 120,
	trailingComma: "all",
	arrowParens: "avoid",
	plugins: ["@trivago/prettier-plugin-sort-imports"],
	importOrder: [
		"^react$",
		"^react-(.*)$",
		"<THIRD_PARTY_MODULES>",
		"^@kyber/(.*)$",
		"^@kyberswap/(.*)$",
		"^@/(.*)$",
		"^[./]",
	],
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
	importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
	importOrderTypeScriptVersion: "5.0.0",
};
