import { ChainId, Token } from '@vutien/sdk-core'
// a list of tokens by chain
type ChainStringList = {
  readonly [chainId in ChainId]: string
}
const V2_CORE_FACTORY_ADDRESSE = '0x1F98431c8aD98523631AE4a59f267346ea31F984'
export const V2_CORE_FACTORY_ADDRESSES: ChainStringList = {
  [ChainId.MAINNET]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.ROPSTEN]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.RINKEBY]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.GÖRLI]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.KOVAN]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.MATIC]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.MUMBAI]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.BSCTESTNET]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.BSCMAINNET]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.AVAXTESTNET]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.AVAXMAINNET]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.FANTOM]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.CRONOSTESTNET]: V2_CORE_FACTORY_ADDRESSE,
  [ChainId.CRONOS]: V2_CORE_FACTORY_ADDRESSE
}
