import { ChainId, Token } from '@vutien/sdk-core'
// a list of tokens by chain
type ChainStringList = {
  readonly [chainId in ChainId]: string
}
const V2_CORE_FACTORY_ADDRESS = '0x0C7369F931a8D809E443c1d4A5DCe663fF888a73'
export const PRO_AMM_CORE_FACTORY_ADDRESSES: ChainStringList = {
  [ChainId.MAINNET]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.ROPSTEN]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.RINKEBY]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.GÖRLI]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.KOVAN]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.MATIC]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.MUMBAI]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.BSCTESTNET]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.BSCMAINNET]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.AVAXTESTNET]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.AVAXMAINNET]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.FANTOM]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.CRONOSTESTNET]: V2_CORE_FACTORY_ADDRESS,
  [ChainId.CRONOS]: V2_CORE_FACTORY_ADDRESS
}

const NONFUNGIBLE_POSITION_MANAGER_ADDRESS = '0x958935bc8dCB8B4B0aDff4FceB2beb8Bbb117CFc'
export const PRO_AMM_NONFUNGIBLE_POSITION_MANAGER_ADDRESSES: ChainStringList = {
  [ChainId.MAINNET]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.ROPSTEN]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.RINKEBY]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.GÖRLI]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.KOVAN]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.MATIC]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.MUMBAI]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.BSCTESTNET]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.BSCMAINNET]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.AVAXTESTNET]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.AVAXMAINNET]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.FANTOM]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.CRONOSTESTNET]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS,
  [ChainId.CRONOS]: NONFUNGIBLE_POSITION_MANAGER_ADDRESS
}
// const TICK_READER = '0xb4748ce3ca04BE8f7E266dC9E38343A286eB5Ec6' //-- old
const TICK_READER = '0xc4c0a7b11457392f74604d9492593e686ab612b3'

export const PRO_AMM_TICK_READER: ChainStringList = {
  [ChainId.MAINNET]: TICK_READER,
  [ChainId.ROPSTEN]: TICK_READER,
  [ChainId.RINKEBY]: TICK_READER,
  [ChainId.GÖRLI]: TICK_READER,
  [ChainId.KOVAN]: TICK_READER,
  [ChainId.MATIC]: TICK_READER,
  [ChainId.MUMBAI]: TICK_READER,
  [ChainId.BSCTESTNET]: TICK_READER,
  [ChainId.BSCMAINNET]: TICK_READER,
  [ChainId.AVAXTESTNET]: TICK_READER,
  [ChainId.AVAXMAINNET]: TICK_READER,
  [ChainId.FANTOM]: TICK_READER,
  [ChainId.CRONOSTESTNET]: TICK_READER,
  [ChainId.CRONOS]: TICK_READER
}

export const PRO_AMM_INIT_CODE_HASH = '0xd71790a46dff0e075392efbd706356cd5a822a782f46e9859829440065879f81'

const QUOTER = '0xC78e50bcB1675617561287272bb64CDEDAB30b1D'

export const PRO_AMM_QUOTER: ChainStringList = {
  [ChainId.MAINNET]: QUOTER,
  [ChainId.ROPSTEN]: QUOTER,
  [ChainId.RINKEBY]: QUOTER,
  [ChainId.GÖRLI]: QUOTER,
  [ChainId.KOVAN]: QUOTER,
  [ChainId.MATIC]: QUOTER,
  [ChainId.MUMBAI]: QUOTER,
  [ChainId.BSCTESTNET]: QUOTER,
  [ChainId.BSCMAINNET]: QUOTER,
  [ChainId.AVAXTESTNET]: QUOTER,
  [ChainId.AVAXMAINNET]: QUOTER,
  [ChainId.FANTOM]: QUOTER,
  [ChainId.CRONOSTESTNET]: QUOTER,
  [ChainId.CRONOS]: QUOTER
}

const ROUTER = '0x16349caF049589FD97be483Cb547e5ADF0991358'
export const PRO_AMM_ROUTERS: ChainStringList = {
  [ChainId.MAINNET]: ROUTER,
  [ChainId.ROPSTEN]: ROUTER,
  [ChainId.RINKEBY]: ROUTER,
  [ChainId.GÖRLI]: ROUTER,
  [ChainId.KOVAN]: ROUTER,
  [ChainId.MATIC]: ROUTER,
  [ChainId.MUMBAI]: ROUTER,
  [ChainId.BSCTESTNET]: ROUTER,
  [ChainId.BSCMAINNET]: ROUTER,
  [ChainId.AVAXTESTNET]: ROUTER,
  [ChainId.AVAXMAINNET]: ROUTER,
  [ChainId.FANTOM]: ROUTER,
  [ChainId.CRONOSTESTNET]: ROUTER,
  [ChainId.CRONOS]: ROUTER
}
