import type { Timestamp } from './primitives'

export type PreparedActionReason =
  | 'PREPARED_ACTION_REASON_UNSPECIFIED'
  | 'PREPARED_ACTION_REASON_ALREADY_ACTIVE'
  | 'PREPARED_ACTION_REASON_NOT_CURRENT_OWNER'
  | 'PREPARED_ACTION_REASON_ACCOUNT_NOT_ACTIVE'
  | 'PREPARED_ACTION_REASON_ACCOUNT_NOT_STOPPED'
  | 'PREPARED_ACTION_REASON_ACCOUNT_PERMANENTLY_PAUSED'
  | 'PREPARED_ACTION_REASON_EXIT_IN_PROGRESS'
  | 'PREPARED_ACTION_REASON_EXIT_NOT_TERMINAL'
  | 'PREPARED_ACTION_REASON_SOURCE_STALE'
  | 'PREPARED_ACTION_REASON_SOURCE_COVERAGE_PENDING'
  | 'PREPARED_ACTION_REASON_FACTORY_PAUSED'
  | 'PREPARED_ACTION_REASON_FEE_POLICY_CHANGED'
  | 'PREPARED_ACTION_REASON_SIGNER_POLICY_CHANGED'
  | 'PREPARED_ACTION_REASON_REQUEST_ID_CONFLICT'
  | 'PREPARED_ACTION_REASON_UNSUPPORTED_ACCOUNT_GENERATION'
  | 'PREPARED_ACTION_REASON_NO_QUOTE_BALANCE'
  | 'PREPARED_ACTION_REASON_INSUFFICIENT_QUOTE_BALANCE'
  | 'PREPARED_ACTION_REASON_INSUFFICIENT_QUOTE_ALLOWANCE'
  | 'PREPARED_ACTION_REASON_CONTROLLER_PAUSED'
  | 'PREPARED_ACTION_REASON_COPY_RUN_STOPPED'
  | 'PREPARED_ACTION_REASON_UNSUPPORTED_QUOTE_TOKEN'
  | 'PREPARED_ACTION_REASON_AMOUNT_BELOW_MINIMUM'
  | 'PREPARED_ACTION_REASON_INVALID_STOP_INTENT'
  | 'PREPARED_ACTION_REASON_NO_EXECUTABLE_ROUTE'
  | 'PREPARED_ACTION_REASON_INNER_CALL_REVERTED'
  | 'PREPARED_ACTION_REASON_NO_SELLABLE_BASE'
  | 'PREPARED_ACTION_REASON_NO_PENDING_SELL_OBLIGATION'
  | 'PREPARED_ACTION_REASON_SELL_OBLIGATION_CHANGED'
  | 'PREPARED_ACTION_REASON_POSITION_NOT_OPEN'
  | 'PREPARED_ACTION_REASON_CLOSE_NOT_ELIGIBLE'

export type AdvisoryActionStatus =
  | 'ADVISORY_ACTION_STATUS_UNSPECIFIED'
  | 'ADVISORY_ACTION_STATUS_AVAILABLE'
  | 'ADVISORY_ACTION_STATUS_PENDING'
  | 'ADVISORY_ACTION_STATUS_UNAVAILABLE'
  | 'ADVISORY_ACTION_STATUS_TRY_PREPARE'

export type AdvisoryActionAvailability = {
  status?: AdvisoryActionStatus
  reason?: PreparedActionReason
  asOf?: Timestamp
}
