blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/NB3vc8J9uv
    about: Please ask and answer questions here
  - name: Telegram
    url: https://t.me/kybernetwork
    about: Kyber Network Official



